project:
  type: website

website:
  title: "**Endangered Languages**"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Visual Analysis
      - href: models.qmd
        text: Quantitative Analysis
      - sources.qmd
      - about.qmd
      

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



