project:
  type: website

website:
  title: "**Endangered Languages Around the World**"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - models.qmd
      - sources.qmd
      - about.qmd
      

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



